const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Bird: 0},
	{ButtonPlay: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{Background: 0},
	{Scored: 0},
	{BottomPipe: 0},
	{TopPipe: 0},
	{ScoreText: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{GameOverText: 0},
	{GameOverScore: 0},
	{ButtonRestart: 0},
	{LocalStorage: 0},
	{HighScoreText: 0},
	{MainTitleText: 0},
	{Bird2: 0},
	{Sine: 0},
	{HowToPlayTxt: 0},
	{HowToTxt_1: 0},
	{HowToTxt_2: 0},
	{ButtonQuit: 0},
	{NewScoreText: 0},
	{TiledBackground3: 0},
	{StartMessageText: 0},
	{coin: 0},
	{EnergyText: 0},
	{sonic: 0},
	{Bg2: 0},
	{Keyboard: 0},
	{SecondsPerObstacle: 0},
	{JumpStrength: 0},
	{SCROLLSPEED: 0},
	{GameOver: 0},
	{HighScore: 0},
	{Score: 0},
	{Energy: 0},
	{BirdColour: 0}
];

self.InstanceType = {
	Bird: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	BottomPipe: class extends self.ISpriteInstance {},
	TopPipe: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	GameOverText: class extends self.ITextInstance {},
	GameOverScore: class extends self.ITextInstance {},
	ButtonRestart: class extends self.IButtonInstance {},
	LocalStorage: class extends self.IInstance {},
	HighScoreText: class extends self.ITextInstance {},
	MainTitleText: class extends self.ISpriteInstance {},
	Bird2: class extends self.ISpriteInstance {},
	HowToPlayTxt: class extends self.ITextInstance {},
	HowToTxt_1: class extends self.ITextInstance {},
	HowToTxt_2: class extends self.ITextInstance {},
	ButtonQuit: class extends self.IButtonInstance {},
	NewScoreText: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	StartMessageText: class extends self.ITextInstance {},
	coin: class extends self.ISpriteInstance {},
	EnergyText: class extends self.ITextInstance {},
	sonic: class extends self.ISpriteInstance {},
	Bg2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {}
}