const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.Dictionary,
		C3.Plugins.AJAX,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.scrollx,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{MooseHead: 0},
	{slot: 0},
	{free: 0},
	{UISlot: 0},
	{Tween: 0},
	{ScreenManager: 0},
	{Sine: 0},
	{UIScreenChangeRight: 0},
	{pickable: 0},
	{Pickup: 0},
	{Touch: 0},
	{DragDrop: 0},
	{Item: 0},
	{UITip: 0},
	{TipsDict: 0},
	{AJAX: 0},
	{Bookcase: 0},
	{Fireplace: 0},
	{Book: 0},
	{BackgroundStars: 0},
	{BookCloseUp: 0},
	{Fader: 0},
	{UIScreenChangeLeft: 0},
	{Painting: 0},
	{Door: 0},
	{Cabinet: 0},
	{CabinetCloseUp: 0},
	{drawerID: 0},
	{DrawerOpener: 0},
	{CabinetBG: 0},
	{hasBatteries: 0},
	{RemoteOverlapCheck: 0},
	{KeypadCloseUp: 0},
	{key: 0},
	{UIKey: 0},
	{Flash: 0},
	{UIKeypadScreen: 0},
	{Keypad: 0},
	{UITutorial: 0},
	{inputFocus: 0},
	{par_uid: 0},
	{par_text: 0},
	{par_duration: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	MooseHead: class extends self.ISpriteInstance {},
	UISlot: class extends self.ISpriteInstance {},
	ScreenManager: class extends self.ISpriteInstance {},
	UIScreenChangeRight: class extends self.ISpriteInstance {},
	Pickup: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Item: class extends self.ISpriteInstance {},
	UITip: class extends self.ISpriteFontInstance {},
	TipsDict: class extends self.IDictionaryInstance {},
	AJAX: class extends self.IInstance {},
	Bookcase: class extends self.ISpriteInstance {},
	Fireplace: class extends self.ISpriteInstance {},
	Book: class extends self.ISpriteInstance {},
	BackgroundStars: class extends self.ITiledBackgroundInstance {},
	BookCloseUp: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	UIScreenChangeLeft: class extends self.ISpriteInstance {},
	Painting: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	Cabinet: class extends self.ISpriteInstance {},
	CabinetCloseUp: class extends self.ISpriteInstance {},
	DrawerOpener: class extends self.ISpriteInstance {},
	CabinetBG: class extends self.ISpriteInstance {},
	RemoteOverlapCheck: class extends self.ISpriteInstance {},
	KeypadCloseUp: class extends self.ISpriteInstance {},
	UIKey: class extends self.ISpriteFontInstance {},
	UIKeypadScreen: class extends self.ISpriteFontInstance {},
	Keypad: class extends self.ISpriteInstance {},
	UITutorial: class extends self.ISpriteFontInstance {}
}